[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm start"
  targetPort = 5173

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  NODE_ENV = "production"
